### ISSUE TITLE
Gamma Correct might not be best enabled by default

### ISSUE THREAD

**Issue by thekovic** [d64u/doom64ultra#2]
Trying out on emulator, Gamma Correct option causes notable grain in black areas and generally washes out the colors. I think enabling it by default might be presenting an unflattering visual to users.

![image](https://github.com/d64u/doom64ultra/assets/72971433/8e9d3518-d521-44ec-a786-6469a149f160)
![image](https://github.com/d64u/doom64ultra/assets/72971433/10095eb1-ad79-4bb0-8331-1c74812fe135)

**Comment by 9nova** [comment]
Disabled it in 1db69669c3559433d0c006e48cc4c2e58443306d by turning up the allowable brightness range, gamma correct is still in as an option
