### ISSUE TITLE
Loading saves seems to give extra weapons

### ISSUE THREAD

**Issue by thekovic** [d64u/doom64ultra#3]
Consider the following save. I made it after completing MAP01, exiting the level with a pistol and a shotgun. Loading the save spawns me at the start of MAP02 with a pistol, a shotgun, a super shotgun, and a chaingun. The two latter weapons not even being collectable in MAP01.
[DOOM 64 ULTRA-9044D7B3.zip](https://github.com/d64u/doom64ultra/files/12806803/DOOM.64.ULTRA-9044D7B3.zip)

**Comment by 9nova** [comment]
Fixed in 424063ccd06f807022d60329c3ad689f7d097e32
